name: hsf-india
channels:
  - defaults
  - nvidia/label/cuda-11.8.0
dependencies:
  - cuda=11.8
  - cudnn=8.9.2
  - cuda-nvcc
      
variables:
  LD_LIBRARY_PATH: "'$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/'"
  XLA_FLAGS: "'--xla_gpu_cuda_data_dir=$CONDA_PREFIX/'"

  
