name: hsf-india
channels:
  - defaults
  - nvidia/label/cuda-12.4.0
dependencies:
  - python=3.11
  - cuda=12.4 
  - cudnn=8.9.7
  - cuda-nvcc
  - pip
  - zstandard
  - zstd
  - clang-tools
  - fsspec
  - lz4
  - pyarrow
  - python-xxhash
  # rapids drops support for the SSL/River GPUs after this release..
  - rapidsai::cudf=23.12.00
  - pip:
      - tensorflow==2.16.1
      - tensorrt
      - astunparse
      - awkward
      - dask
      - dask-awkward
      - distributed
      - h5py
      - hepunits
      - hist
      - ipympl
      - jupyterlab-deck
      - jupyterlab-mathjax3
      - matplotlib
      - numba
      - numexpr
      - numpy
      - pandas
      - particle
      - protobuf
      - pycuda
      - pybind11
      - scikit-learn
      - tables
      - uproot
      - vector
      - mplhep
      - requests
      - aiohttp
      - jax[cpu]
      - graphviz
      - dask-labextension==6.2.0
      - torch==2.3.0
      - torchvision
      - torchvision
      - torchaudio
      
variables:
  LD_LIBRARY_PATH: "'$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/'"
  XLA_FLAGS: "'--xla_gpu_cuda_data_dir=$CONDA_PREFIX/'"
# not needed for Delhi setup
#  NUMBA_CUDA_ENABLE_MINOR_VERSION_COMPATIBILITY: "1"
  
